from __future__ import annotations

# ASCII-only source with Unicode escapes to avoid Windows shell encoding corruption.

class UI:
    VIEW_TOOLBAR = '보기 도구'
    DOC_TOOLBAR = '문서 도구'

    BTN_OCR = 'OCR'
    BTN_SNAPSHOT = '스냅샷'
    BTN_NOTE_LIST = '메모목록'
    BTN_BOOK_VIEW = '책 보기'
    BTN_APPLY = 'PDF에 적용'
    BTN_DISCARD = '취소'

    TIP_OCR = 'OCR 패널 열기/닫기 (Ctrl+Shift+O)'
    TIP_SNAPSHOT = '현재 화면을 스냅샷으로 저장 (Ctrl+Shift+C)'
    TIP_NOTE_LIST = '오른쪽 메모 목록 패널 열기'
    TIP_BOOK_VIEW = '책 보기 모드 켜기/끄기 (Ctrl+Shift+B)'
    TIP_APPLY = '보류 중인 변경사항을 실제 PDF에 적용 (Ctrl+Shift+A)'
    TIP_DISCARD = '보류 중인 변경사항을 버립니다'

    LABEL_VIEW = '보기: '
    VIEW_SINGLE = '한 페이지'
    VIEW_DOUBLE = '양면 보기'
    VIEW_BOOK = '책 보기'
    VIEW_SCROLL = '세로 스크롤'
    VIEW_SEGMENT = '\ud655\ub300 \uc77d\uae30(2\ubd84\ud560)'
    SNAPSHOT_ACTION = '스냅샷'
    TIP_PREV_PAGE = '이전 페이지'
    TIP_NEXT_PAGE = '다음 페이지'
    TIP_GO_PAGE = '\uc785\ub825\ud55c \ud398\uc774\uc9c0\ub85c \uc774\ub3d9'

    MENU_FILE = '파일(&F)'
    MENU_EDIT = '편집(&E)'
    MENU_PAGE = '페이지(&P)'
    MENU_COMPOSE = '구성(&C)'
    MENU_VIEW = '보기(&V)'
    MENU_CALC = '계산기(&K)'
    MENU_PRINT = '인쇄(&R)'
    MENU_EXPORT = '내보내기/변환'
    MENU_PDF_UTIL = 'PDF 유틸리티'
    MENU_LAW_CALC = '법률 계산기'
    MENU_FIND = '찾기(&D)'

    ACT_NEW = '새 문서(&N)'
    ACT_OPEN = '열기(&O)...'
    ACT_SAVE = '저장(&S)'
    ACT_SAVE_AS = '다른 이름으로 저장'
    ACT_PRINT = '인쇄...'
    ACT_EXIT = '종료'
    ACT_UNDO = '실행 취소'
    ACT_TEXT_EDITOR = '텍스트 편집 열기'
    ACT_TEXT_REPLACE = '텍스트 찾기/바꾸기'
    ACT_FIND = '찾기...'
    ACT_FIND_NEXT = '다음 찾기'
    ACT_FIND_PREV = '이전 찾기'
    ACT_FIND_ADVANCED = '고급 검색 (결과 목록)...'
    ACT_FIND_CLEAR = '검색 강조 지우기'
    ACT_DICT = '사전 창 열기'
    ACT_PREFS = '환경설정'
    ACT_INSERT_BLANK = '빈 페이지 추가'
    ACT_INSERT_IMAGE_PAGE = '이미지로 페이지 추가'
    ACT_DELETE_PAGE = '현재 페이지 삭제'
    ACT_CROP_PAGE = '현재 페이지 자르기'
    ACT_ROTATE_CW = '시계 방향 회전'
    ACT_ROTATE_CCW = '반시계 방향 회전'
    ACT_SPLIT_PDF = 'PDF 분할'
    ACT_MERGE_PDF = 'PDF 병합'
    ACT_WATERMARK = '워터마크 추가'
    ACT_HEADER_FOOTER = '머리말/꼬리말'
    ACT_OCR_PANEL = 'OCR 패널 열기'
    ACT_SNAPSHOT_PANEL = '스냅샷 창 보기'
    ACT_NOTE_PANEL = '메모 목록 열기'
    ACT_BOOK_VIEW = '책 보기'
    ACT_FIT_PAGE = '페이지에 맞춤'
    ACT_FIT_WIDTH = '너비에 맞춤'
    ACT_ACTUAL_SIZE = '실제 크기 (100%)'
    ACT_CALC_NORMAL = '일반 계산기'
    ACT_CALC_ENGINEERING = '공학 계산기'
    ACT_CALC_UNIT = '단위 계산기'
    ACT_CALC_DATE = '날짜 계산기'
    ACT_CALC_DELAY = '지연이자'
    ACT_CALC_STAMP = '인지세 계산'
    ACT_CALC_RATIO = '비율 계산/환산'
    ACT_CALC_AGE = '연령 계산'
    ACT_CALC_RETIRE = '퇴직금 계산'
    ACT_CALC_LAWSUIT = '소송비용 계산'
    ACT_CALC_INTEREST = '이자 계산'
    ACT_CALC_SALARY = '월급 계산'
    ACT_CALC_INHERIT = '상속세 계산'
    ACT_CALC_OPEN = '일반 계산기 열기 (Ctrl+Shift+K)'

    CTX_DICT = '사전 검색: "{word}"'
    CTX_NOTE = '메모 추가'
    CTX_TEXT = '텍스트 추가'
    CTX_DELETE = '주석 삭제'
